GestCantineADA/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cantine/', include('cantine.urls')),
]

cantine/urls.py
# urls.py
from django.urls import path
from .views.menu_view import menu_list, create_menu, menu_list, menu_detail, update_menu, delete_menu
from .views.plat_view import plat_list, plat_detail,create_plat, plat_list, plat_detail, update_plat, delete_plat


app_name = 'cantine'
urlpatterns = [
    
    #Routes pour Plats 
    path('plat/', plat_list, name='plat_list'),
    path('plat/<int:pk>/', plat_detail, name='plat_detail'),
    path('plat/new/', create_plat, name='create_plat'),
    path('plat/<int:pk>/edit/', update_plat, name='update_plat'),
    path('plat/<int:pk>/delete/', delete_plat, name='delete_plat'),
    
    
    #Routes pour Menus

    path('menu/', menu_list, name='menu_list'),
    path('menu/<int:pk>/', menu_detail, name='menu_detail'),
    path('menu/new/', create_menu, name='create_menu'),
    path('menu/<int:pk>/edit/', update_menu, name='update_menu'),
    path('menu/<int:pk>/delete/', delete_menu, name='delete_menu'),

]

cantine/models/menu_model.py
from django.db import models

class Menu(models.Model):
    id = models.AutoField(primary_key=True)
    creation_date = models.DateField()

    def __str__(self):
        return f"Menu {self.id}"

cantine/models/plat_model.py
from django.db import models
from .menu_model import Menu
class Plat(models.Model):
    id = models.OneToOneField(Menu, on_delete=models.CASCADE, primary_key=True, related_name='plat')
    name = models.CharField(max_length=255)
    summary = models.TextField()

    def __str__(self):
        return self.name

cantine/forms.py
from django import forms
from .models import Plat
from .models import Menu

class PlatForm(forms.ModelForm):
    class Meta:
        model = Plat
        fields = ['name', 'summary']



class MenuForm(forms.ModelForm):
    class Meta:
        model = Menu
        fields = ['creation_date']

cantine/views/cantine_view.py
from django.shortcuts import render,redirect



def index(request):
     # Logique pour préparer le contexte si nécessaire
    context = {}  # Ajoute des données au contexte si besoin
    return render(request, "cantine/index.html", context)
    

cantine/views/menu_view.py
from django.shortcuts import render, get_object_or_404, redirect
from ..models.menu_model import Menu
from ..forms import MenuForm


# Create View
def create_menu(request):
    if request.method == 'POST':
        form = MenuForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('menu_list')
    else:
        form = MenuForm()
    return render(request, 'menu_form.html', {'form': form})

# Read View
def menu_list(request):
    menus = Menu.objects.all()
    return render(request, 'cantine/index.html', {'menus': menus})

def menu_detail(request, pk):
    menu = get_object_or_404(Menu, pk=pk)
    return render(request, 'menu_detail.html', {'menu': menu})

# Update View
def update_menu(request, pk):
    menu = get_object_or_404(Menu, pk=pk)
    if request.method == 'POST':
        form = MenuForm(request.POST, instance=menu)
        if form.is_valid():
            form.save()
            return redirect('cantine:menu_list')
    else:
        form = MenuForm(instance=menu)
    return render(request, 'menu_form.html', {'form': form})

# Delete View
def delete_menu(request, pk):
    menu = get_object_or_404(Menu, pk=pk)
    if request.method == 'POST':
        menu.delete()
        return redirect('menu_list')
    return render(request, 'menu_confirm_delete.html', {'menu': menu})

cantine/views/plat_view.py
from django.shortcuts import render, get_object_or_404,redirect
from ..models.plat_model import Plat
from ..forms import PlatForm

def plat_list(request):
    plats = Plat.objects.all()
    return render(request, 'cantine/plats.html', {'plats': plats})

def plat_detail(request, plat_id):
    plat = get_object_or_404(Plat, id=plat_id)
    return render(request, 'cantine/plat_detail.html', {'plat': plat})



# Create View
def create_plat(request):
    if request.method == 'POST':
        form = PlatForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('plat_list')
    else:
        form = PlatForm()
    return render(request, 'plat_form.html', {'form': form})

# Read View
def plat_list(request):
    plats = Plat.objects.all()
    return render(request, 'plat_list.html', {'plats': plats})

def plat_detail(request, pk):
    plat = get_object_or_404(Plat, pk=pk)
    return render(request, 'plat_detail.html', {'plat': plat})

# Update View
def update_plat(request, pk):
    plat = get_object_or_404(Plat, pk=pk)
    if request.method == 'POST':
        form = PlatForm(request.POST, instance=plat)
        if form.is_valid():
            form.save()
            return redirect('plat_list')
    else:
        form = PlatForm(instance=plat)
    return render(request, 'plat_form.html', {'form': form})

# Delete View
def delete_plat(request, pk):
    plat = get_object_or_404(Plat, pk=pk)
    if request.method == 'POST':
        plat.delete()
        return redirect('plat_list')
    return render(request, 'plat_confirm_delete.html', {'plat': plat})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
   <head>
      <meta charset="utf-8" />
      <meta
         name="viewport"
         content="width=device-width, initial-scale=1, shrink-to-fit=no"
      />
      <link
         rel="apple-touch-icon"
         sizes="76x76"
         href="{% static 'img/apple-icon.png' %}"
      />
      <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}" />
      <title>{% block title %}Ma cantine{% endblock %}</title>
      <link
         rel="stylesheet"
         type="text/css"
         href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700"
      />
      <link href="{% static 'css/nucleo-icons.css' %}" rel="stylesheet" />
      <link href="{% static 'css/nucleo-svg.css' %}" rel="stylesheet" />
      <script
         src="https://kit.fontawesome.com/42d5adcbca.js"
         crossorigin="anonymous"
      ></script>
      <link
         href="https://fonts.googleapis.com/icon?family=Material+Icons+Round"
         rel="stylesheet"
      />
      <link
         rel="stylesheet"
         href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0"
      />
      <link
         id="pagestyle"
         href="{% static 'css/material-dashboard.css' %}"
         rel="stylesheet"
      />
      <script
         defer
         data-site="YOUR_DOMAIN_HERE"
         src="https://api.nepcha.com/js/nepcha-analytics.js"
      ></script>
   </head>

   <body class="g-sidenav-show bg-gray-200">
      <!-- partials/sidebar.html -->
      <aside
         class="sidenav navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-3 bg-gradient-dark"
         id="sidenav-main"
      >
         <div class="sidenav-header">
            <i
               class="fas fa-times p-3 cursor-pointer text-white opacity-5 position-absolute end-0 top-0 d-none d-xl-none"
               aria-hidden="true"
               id="iconSidenav"
            ></i>
            <a
               class="navbar-brand m-0"
               href="{% url 'cantine:menu_list' %}"
               target="_blank"
            >
               <img
                  src="{% static 'img/logo-ct.png' %}"
                  class="navbar-brand-img h-100"
                  alt="main_logo"
               />
               <span class="ms-1 font-weight-bold text-white">Ma cantine</span>
            </a>
         </div>
         <hr class="horizontal light mt-0 mb-2" />
         <div
            class="collapse navbar-collapse w-auto"
            id="sidenav-collapse-main"
         >
            <ul class="navbar-nav">
               <li class="nav-item">
                  <a
                     class="nav-link text-white"
                     href="{% url 'cantine:menu_list' %}"
                  >
                     <div
                        class="text-white text-center me-2 d-flex align-items-center justify-content-center"
                     >
                        <span class="material-symbols-outlined">menu_book</span>
                     </div>
                     <span class="nav-link-text ms-1">Menus</span>
                  </a>
               </li>
               <li class="nav-item">
                  <a
                     class="nav-link text-white"
                     href="{% url 'cantine:plat_list' %}"
                  >
                     <div
                        class="text-white text-center me-2 d-flex align-items-center justify-content-center"
                     >
                        <span class="material-symbols-outlined"
                           >local_cafe</span
                        >
                     </div>
                     <span class="nav-link-text ms-1">Plats</span>
                  </a>
               </li>
            </ul>
         </div>
      </aside>

      <main
         class="main-content position-relative max-height-vh-100 h-100 border-radius-lg"
      >
         <nav
            class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl"
            id="navbarBlur"
            data-scroll="true"
         >
            <div class="container-fluid py-1 px-3">
               <div
                  class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4"
                  id="navbar"
               >
                  <ul class="navbar-nav justify-content-start">
                     <li class="nav-item d-flex align-items-center">
                        <a
                           class="btn btn-outline-warning btn-sm mb-0 me-3"
                           href="#"
                           >Ajouter un plat</a
                        >
                     </li>
                  </ul>
                  <div class="ms-md-auto pe-md-3 d-flex align-items-center">
                     <div class="input-group input-group-outline">
                        <label class="form-label">Recherche par nom</label>
                        <input type="text" class="form-control" />
                     </div>
                  </div>
                  <ul class="navbar-nav justify-content-end">
                     <li class="nav-item d-flex align-items-center">
                        <button
                           class="btn btn-outline-primary btn-sm mb-0 me-3"
                        >
                           Recherche
                        </button>
                     </li>
                  </ul>
               </div>
            </div>
         </nav>

         <div class="container-fluid py-4">
            {% block content %}{% endblock %}
         </div>
         <div class="container-fluid py-4">
            <footer class="footer py-4">
               <div class="container-fluid">
                  <div
                     class="row align-items-center justify-content-lg-between"
                  >
                     <div class="col-lg-6 mb-lg-0 mb-4">
                        <div
                           class="copyright text-center text-sm text-muted text-lg-start"
                        >
                           ©
                           <script>
                              document.write(new Date().getFullYear());
                           </script>
                           ADA
                        </div>
                     </div>
                  </div>
               </div>
            </footer>
         </div>
      </main>
      <script src="{% static 'js/core/popper.min.js' %}"></script>
      <script src="{% static 'js/core/bootstrap.min.js' %}"></script>
      <script src="{% static 'js/plugins/perfect-scrollbar.min.js' %}"></script>
      <script src="{% static 'js/plugins/smooth-scrollbar.min.js' %}"></script>
      <script>
         var win = navigator.platform.indexOf('Win') > -1;
         if (win && document.querySelector('#sidenav-scrollbar')) {
            var options = { damping: '0.5' };
            Scrollbar.init(
               document.querySelector('#sidenav-scrollbar'),
               options
            );
         }
      </script>
      <script async defer src="https://buttons.github.io/buttons.js"></script>
      <script src="{% static 'js/material-dashboard.min.js' %}"></script>
   </body>
</html>

templates/cantine/forms.html
{% extends "base.html" %} {% load static %} {% block title %} Formulaire {%
endblock %} {% block head %} {{ block.super }}
<link
   rel="apple-touch-icon"
   sizes="76x76"
   href="{% static 'img/apple-icon.png' %}"
/>
<link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}" />
<link
   rel="stylesheet"
   href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0"
/>
<link
   id="pagestyle"
   href="{% static 'assets/css/material-dashboard.css?v=3.1.0' %}"
   rel="stylesheet"
/>
<script
   defer
   data-site="YOUR_DOMAIN_HERE"
   src="https://api.nepcha.com/js/nepcha-analytics.js"
></script>
{% endblock %} {% block content %}
<body class="g-sidenav-show bg-gray-200">
   <aside
      class="sidenav navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-3 bg-gradient-dark"
      id="sidenav-main"
   >
      <div class="sidenav-header">
         <i
            class="fas fa-times p-3 cursor-pointer text-white opacity-5 position-absolute end-0 top-0 d-none d-xl-none"
            aria-hidden="true"
            id="iconSidenav"
         ></i>
         <a class="navbar-brand m-0" href="{% url 'cantine:index' %}" target="_blank">
            <img
               src="{% static 'img/logo-ct.png' %}"
               class="navbar-brand-img h-100"
               alt="main_logo"
            />
            <span class="ms-1 font-weight-bold text-white">Ma cantine</span>
         </a>
      </div>

      <hr class="horizontal light mt-0 mb-2" />

      <div class="collapse navbar-collapse w-auto" id="sidenav-collapse-main">
         <ul class="navbar-nav">
            <li class="nav-item">
               <a class="nav-link text-white" href="{% url 'menus' %}">
                  <div
                     class="text-white text-center me-2 d-flex align-items-center justify-content-center"
                  >
                     <span class="material-symbols-outlined">menu_book</span>
                  </div>
                  <span class="nav-link-text ms-1">Menus</span>
               </a>
            </li>
            <li class="nav-item">
               <a class="nav-link text-white" href="{% url 'plats' %}">
                  <div
                     class="text-white text-center me-2 d-flex align-items-center justify-content-center"
                  >
                     <span class="material-symbols-outlined">local_cafe</span>
                  </div>
                  <span class="nav-link-text ms-1">Plats</span>
               </a>
            </li>
         </ul>
      </div>
   </aside>

   <main class="main-content mt-0">
      <section>
         <div class="page-header min-vh-100">
            <div class="container">
               <div class="row">
                  <div
                     class="col-xl-12 col-lg-12 col-md-12 d-flex flex-column ms-auto me-auto ms-lg-auto me-lg-12"
                  >
                     <div class="card card-plain">
                        <div class="card-header">
                           <h4 class="font-weight-bolder">
                              Formulaire d'enregistrement
                           </h4>
                        </div>
                        <div class="card-body">
                           <form role="form">
                              <div class="input-group input-group-outline mb-3">
                                 <label class="form-label">Libelle</label>
                                 <input type="text" class="form-control" />
                              </div>
                              <div class="input-group input-group-outline mb-3">
                                 <input type="date" class="form-control" />
                              </div>
                              <div class="text-center">
                                 <button
                                    type="button"
                                    class="btn btn-lg bg-gradient-primary btn-lg w-100 mt-4 mb-0"
                                 >
                                    Enregistrer
                                 </button>
                              </div>
                           </form>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </section>
   </main>

   {% endblock %} {% block scripts %} {{ block.super }}
   <script src="{% static 'js/core/popper.min.js' %}"></script>
   <script src="{% static 'js/core/bootstrap.min.js' %}"></script>
   <script src="{% static 'js/plugins/perfect-scrollbar.min.js' %}"></script>
   <script src="{% static 'js/plugins/smooth-scrollbar.min.js' %}"></script>
   <script>
      var win = navigator.platform.indexOf('Win') > -1;
      if (win && document.querySelector('#sidenav-scrollbar')) {
         var options = { damping: '0.5' };
         Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
      }
   </script>
   <script async defer src="https://buttons.github.io/buttons.js"></script>
   <script src="{% static 'js/material-dashboard.min.js' %}"></script>
   {% endblock %}
</body>

templates/cantine/index.html
{% extends "base.html" %} {% load static %} {% block title %} Ma cantine
scolaire {% endblock %} {% block head %}
<meta charset="utf-8" />
<meta
   name="viewport"
   content="width=device-width, initial-scale=1, shrink-to-fit=no"
/>

<link
   rel="apple-touch-icon"
   sizes="76x76"
   href="{% static 'img/apple-icon.png' %}"
/>
<link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}" />

<!-- Fonts and icons -->
<link
   rel="stylesheet"
   type="text/css"
   href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700"
/>
<link
   rel="stylesheet"
   href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0"
/>

<!-- Nucleo Icons -->
<link href="{% static 'css/nucleo-icons.css' %}" rel="stylesheet" />
<link href="{% static 'css/nucleo-svg.css' %}" rel="stylesheet" />

<!-- Font Awesome Icons -->
<script
   src="https://kit.fontawesome.com/42d5adcbca.js"
   crossorigin="anonymous"
></script>

<!-- Material Icons -->
<link
   href="https://fonts.googleapis.com/icon?family=Material+Icons+Round"
   rel="stylesheet"
/>

<!-- CSS Files -->
<link
   id="pagestyle"
   href="{% static 'css/material-dashboard.css?v=3.1.0' %}"
   rel="stylesheet"
/>

<!-- Nepcha Analytics (nepcha.com) -->
<script
   defer
   data-site="YOUR_DOMAIN_HERE"
   src="https://api.nepcha.com/js/nepcha-analytics.js"
></script>
{% endblock %} {% block content %}
<body class="g-sidenav-show bg-gray-100">
   <aside
      class="sidenav navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-3 bg-gradient-dark"
      id="sidenav-main"
   >
      <div class="sidenav-header">
         <i
            class="fas fa-times p-3 cursor-pointer text-white opacity-5 position-absolute end-0 top-0 d-none d-xl-none"
            aria-hidden="true"
            id="iconSidenav"
         ></i>
         <a
            class="navbar-brand m-0"
            href="{% url 'cantine:index' %}"
            target="_blank"
         >
            <img
               src="{% static 'img/logo-ct.png' %}"
               class="navbar-brand-img h-100"
               alt="main_logo"
            />
            <span class="ms-1 font-weight-bold text-white">Ma cantine</span>
         </a>
      </div>

      <hr class="horizontal light mt-0 mb-2" />

      <div class="collapse navbar-collapse w-auto" id="sidenav-collapse-main">
         <ul class="navbar-nav">
            <li class="nav-item">
               <a
                  class="nav-link text-white"
                  href="{% url 'cantine:menu_list' %}"
               >
                  <div
                     class="text-white text-center me-2 d-flex align-items-center justify-content-center"
                  >
                     <span class="material-symbols-outlined">menu_book</span>
                  </div>
                  <span class="nav-link-text ms-1">Menus</span>
               </a>
            </li>
            <li class="nav-item">
               <a
                  class="nav-link text-white"
                  href="{% url 'cantine:plat_list' %}"
               >
                  <div
                     class="text-white text-center me-2 d-flex align-items-center justify-content-center"
                  >
                     <span class="material-symbols-outlined">local_cafe</span>
                  </div>
                  <span class="nav-link-text ms-1">Plats</span>
               </a>
            </li>
         </ul>
      </div>
   </aside>

   <main class="main-content border-radius-lg">
      <div class="container-fluid py-4">
         <!-- Your page content goes here -->
         {% block page_content %}
         <!-- Default content if no block is defined -->
         {% endblock %}

         <footer class="footer py-4">
            <div class="container-fluid">
               <div class="row align-items-center justify-content-lg-between">
                  <div class="col-lg-6 mb-lg-0 mb-4">
                     <div
                        class="copyright text-center text-sm text-muted text-lg-start"
                     >
                        ©
                        <script>
                           document.write(new Date().getFullYear());
                        </script>
                        ADA
                     </div>
                  </div>
               </div>
            </div>
         </footer>
      </div>
   </main>

   {% endblock %} {% block scripts %}
   <!-- Core JS Files -->
   <script src="{% static 'js/core/popper.min.js' %}"></script>
   <script src="{% static 'js/core/bootstrap.min.js' %}"></script>
   <script src="{% static 'js/plugins/perfect-scrollbar.min.js' %}"></script>
   <script src="{% static 'js/plugins/smooth-scrollbar.min.js' %}"></script>
   <script>
      var win = navigator.platform.indexOf('Win') > -1;
      if (win && document.querySelector('#sidenav-scrollbar')) {
         var options = { damping: '0.5' };
         Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
      }
   </script>
   <script async defer src="https://buttons.github.io/buttons.js"></script>
   <script src="{% static 'js/material-dashboard.min.js' %}"></script>
   {% endblock %}
</body>

templates/cantine/menus.html
{% extends 'base.html' %} {% load static %} {% block title %}Liste des menus{%
endblock %} {% block content %}
<body class="g-sidenav-show bg-gray-200">
   <aside
      class="sidenav navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-3 bg-gradient-dark"
      id="sidenav-main"
   >
      <div class="sidenav-header">
         <i
            class="fas fa-times p-3 cursor-pointer text-white opacity-5 position-absolute end-0 top-0 d-none d-xl-none"
            aria-hidden="true"
            id="iconSidenav"
         ></i>
         <a class="navbar-brand m-0" href="../index.html" target="_blank">
            <img
               src="../img/logo-ct.png"
               class="navbar-brand-img h-100"
               alt="main_logo"
            />
            <span class="ms-1 font-weight-bold text-white">Ma cantine</span>
         </a>
      </div>
      <hr class="horizontal light mt-0 mb-2" />
      <div class="collapse navbar-collapse w-auto" id="sidenav-collapse-main">
         <ul class="navbar-nav">
            <li class="nav-item">
               <a class="nav-link text-white" href="menus.html">
                  <div
                     class="text-white text-center me-2 d-flex align-items-center justify-content-center"
                  >
                     <span class="material-symbols-outlined">menu_book</span>
                  </div>
                  <span class="nav-link-text ms-1">Menus</span>
               </a>
            </li>
            <li class="nav-item">
               <a class="nav-link text-white" href="plats.html">
                  <div
                     class="text-white text-center me-2 d-flex align-items-center justify-content-center"
                  >
                     <span class="material-symbols-outlined">local_cafe</span>
                  </div>
                  <span class="nav-link-text ms-1">Plats</span>
               </a>
            </li>
         </ul>
      </div>
   </aside>
   <main
      class="main-content position-relative max-height-vh-100 h-100 border-radius-lg"
   >
      <!-- Navbar -->
      <nav
         class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl"
         id="navbarBlur"
         data-scroll="true"
      >
         <div class="container-fluid py-1 px-3">
            <div
               class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4"
               id="navbar"
            >
               <ul class="navbar-nav justify-content-start">
                  <li class="nav-item d-flex align-items-center">
                     <a
                        class="btn btn-outline-warning btn-sm mb-0 me-3"
                        href="#"
                        >Ajouter un menu</a
                     >
                  </li>
               </ul>
               <div class="ms-md-auto pe-md-3 d-flex align-items-center">
                  <div class="input-group input-group-outline">
                     <label class="form-label">Recherche par nom</label>
                     <input type="text" class="form-control" />
                  </div>
               </div>
               <ul class="navbar-nav justify-content-end">
                  <li class="nav-item d-flex align-items-center">
                     <button class="btn btn-outline-primary btn-sm mb-0 me-3">
                        Recherche
                     </button>
                  </li>
               </ul>
            </div>
         </div>
      </nav>
      <!-- End Navbar -->
      <div class="container-fluid py-4">
         <div class="row">
            <div class="col-12">
               <div class="card my-4">
                  <div
                     class="card-header p-0 position-relative mt-n4 mx-3 z-index-2"
                  >
                     <div
                        class="bg-gradient-warning shadow-primary border-radius-lg pt-4 pb-3"
                     >
                        <h6 class="text-white text-capitalize ps-3">
                           Liste des menus (1)
                        </h6>
                     </div>
                  </div>
                  <div class="card-body px-0 pb-2">
                     <div class="table-responsive p-0">
                        <table class="table align-items-center mb-0">
                           <thead>
                              <tr>
                                 <th
                                    class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7"
                                 >
                                    Date
                                 </th>
                                 <th
                                    class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7"
                                 >
                                    Plat
                                 </th>
                                 <th
                                    class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2 align-items-center"
                                 ></th>
                              </tr>
                           </thead>
                           <tbody>
                              <tr>
                                 <td>
                                    <div class="d-flex px-2 py-1">
                                       <div
                                          class="d-flex flex-column justify-content-center"
                                       >
                                          <h6 class="mb-0 text-sm">
                                             10/11/2024
                                          </h6>
                                       </div>
                                    </div>
                                 </td>
                                 <td>
                                    <div class="d-flex px-2 py-1">
                                       <div
                                          class="d-flex flex-column justify-content-center"
                                       >
                                          <h6 class="mb-0 text-sm">ATTIEKE</h6>
                                       </div>
                                    </div>
                                 </td>
                                 <td class="align-middle text-center text-sm">
                                    <button
                                       class="badge badge-sm bg-gradient-success"
                                    >
                                       Modifier
                                    </button>
                                    <button
                                       class="badge badge-sm bg-gradient-danger"
                                    >
                                       Supprimer
                                    </button>
                                 </td>
                              </tr>
                           </tbody>
                        </table>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         <footer class="footer py-4">
            <div class="container-fluid">
               <div class="row align-items-center justify-content-lg-between">
                  <div class="col-lg-6 mb-lg-0 mb-4">
                     <div
                        class="copyright text-center text-sm text-muted text-lg-start"
                     >
                        ©
                        <script>
                           document.write(new Date().getFullYear());
                        </script>
                        ADA
                     </div>
                  </div>
               </div>
            </div>
         </footer>
      </div>
   </main>
</body>
{% endblock %}